config/routes.rb
Rails.application.routes.draw do
  resources :ddcs
  resources :attributes
  resources :samples
  resources :create_device_tables

  get 'dashboard', to: 'dashboard#index'

  get 'report', to: 'report#index'

  get 'samples_clear', to: 'samples#clear'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/sample.rb
class Sample < ApplicationRecord
end

app/controllers/samples_controller.rb
class SamplesController < ApplicationController
  before_action :set_sample, only: [:show, :edit, :update, :destroy]

  # GET /samples
  # GET /samples.json
  def index
    @active_ddc = ''
    @active_source = ''
    @ddcs = [ '' ] + Ddc.order(name: :asc).pluck(:name)

    @samples = Sample.order(created_at: :desc).paginate(page: params[:page], total_entries: 1000, per_page: params[:per_page])

    if params[:ddc]
      @samples = @samples.where(ddc: params[:ddc])
      @active_ddc = params[:ddc]
    end

    if params[:source]
      @samples = @samples.where(uuid: params[:source])
      @active_source = params[:source]
    end

    if params[:interval]
      @samples = @samples.where('created_at > ?', Time.now - params[:interval].to_i)
    end

    logger.unknown "SAMPLES INDEX"
    logger.unknown @samples.explain
  end

  # GET /samples/1
  # GET /samples/1.json
  def show
  end

  # GET /samples/new
  def new
    @sample = Sample.new
  end

  # GET /samples/1/edit
  def edit
  end

  # POST /samples
  # POST /samples.json
  def create
    @sample = Sample.new(sample_params)

    respond_to do |format|
      if @sample.save
        format.html { redirect_to @sample, notice: 'Sample was successfully created.' }
        format.json { render :show, status: :created, location: @sample }
      else
        format.html { render :new }
        format.json { render json: @sample.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /samples/1
  # PATCH/PUT /samples/1.json
  def update
    respond_to do |format|
      if @sample.update(sample_params)
        format.html { redirect_to @sample, notice: 'Sample was successfully updated.' }
        format.json { render :show, status: :ok, location: @sample }
      else
        format.html { render :edit }
        format.json { render json: @sample.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /samples/1
  # DELETE /samples/1.json
  def destroy
    @sample.destroy
    respond_to do |format|
      format.html { redirect_to samples_url, notice: 'Sample was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sample
      @sample = Sample.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sample_params
      params.require(:sample).permit(:uuid, :source, :ddc, :data, :interval, :per_page)
    end
end

app/helpers/samples_helper.rb
module SamplesHelper
  def nav_class(topic)
    if topic == @active_topic
      'nav-link active'
    else
      'nav-link'
    end
  end
end

app/views/samples/_form.html.erb
<%= form_with(model: sample, local: true) do |form| %>
  <% if sample.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sample.errors.count, "error") %> prohibited this sample from being saved:</h2>

      <ul>
      <% sample.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :uuid %>
    <%= form.text_field :uuid %>
  </div>

  <div class="field">
    <%= form.label :topic %>
    <%= form.text_field :topic %>
  </div>

  <div class="field">
    <%= form.label :data %>
    <%= form.text_field :data %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/samples/edit.html.erb
<h1>Editing Sample</h1>

<%= render 'form', sample: @sample %>

<%= link_to 'Show', @sample %> |
<%= link_to 'Back', samples_path %>

app/views/samples/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Samples</h1>

<%= bootstrap_form_tag url: samples_path, method: :get do |f| %>
  <%= f.select :ddc, options_for_select(@ddcs, selected: @active_ddc), { hide_label: true }, { class: 'form-control', onchange: 'this.form.submit()' } %>
<% end %>

<table class='table'>
  <thead>
    <tr>
      <th>Source</th>
      <th>DDC</th>
      <th>Sequence</th>
      <th>Data</th>
      <th>created</th>
    </tr>
    <tr>
  </thead>

  <tbody>
    <% @samples.each do |sample| %>
      <tr>
        <td><%= link_to sample.uuid, samples_path(source: sample.uuid)  %></td>
        <td><%= link_to sample.ddc || '', samples_path(ddc: sample.ddc)  %></td>
        <td><%= link_to sample.sequence || '', samples_path(sequence: sample.sequence, source: sample.uuid)  %></td>
        <td><%= sample.data %></td>
	<td><%= sample.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= will_paginate @devices %>

app/views/samples/new.html.erb
<h1>New Sample</h1>

<%= render 'form', sample: @sample %>

<%= link_to 'Back', samples_path %>

app/views/samples/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Uuid:</strong>
  <%= @sample.uuid %>
</p>

<p>
  <strong>Topic:</strong>
  <%= @sample.topic %>
</p>

<p>
  <strong>Data:</strong>
  <%= @sample.data %>
</p>

<%= link_to 'Edit', edit_sample_path(@sample) %> |
<%= link_to 'Back', samples_path %>