config/routes.rb
Rails.application.routes.draw do
  resources :ddcs
  resources :attributes
  resources :samples
  resources :create_device_tables

  get 'dashboard', to: 'dashboard#index'

  get 'report', to: 'report#index'

  get 'samples_clear', to: 'samples#clear'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/create_device_tables_controller.rb
class CreateDeviceTablesController < ApplicationController
  before_action :set_create_device_table, only: [:show, :edit, :update, :destroy]

  # GET /create_device_tables
  # GET /create_device_tables.json
  def index
    @create_device_tables = CreateDeviceTable.all
  end

  # GET /create_device_tables/1
  # GET /create_device_tables/1.json
  def show
  end

  # GET /create_device_tables/new
  def new
    @create_device_table = CreateDeviceTable.new
  end

  # GET /create_device_tables/1/edit
  def edit
  end

  # POST /create_device_tables
  # POST /create_device_tables.json
  def create
    @create_device_table = CreateDeviceTable.new(create_device_table_params)

    respond_to do |format|
      if @create_device_table.save
        format.html { redirect_to @create_device_table, notice: 'Create device table was successfully created.' }
        format.json { render :show, status: :created, location: @create_device_table }
      else
        format.html { render :new }
        format.json { render json: @create_device_table.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /create_device_tables/1
  # PATCH/PUT /create_device_tables/1.json
  def update
    respond_to do |format|
      if @create_device_table.update(create_device_table_params)
        format.html { redirect_to @create_device_table, notice: 'Create device table was successfully updated.' }
        format.json { render :show, status: :ok, location: @create_device_table }
      else
        format.html { render :edit }
        format.json { render json: @create_device_table.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /create_device_tables/1
  # DELETE /create_device_tables/1.json
  def destroy
    @create_device_table.destroy
    respond_to do |format|
      format.html { redirect_to create_device_tables_url, notice: 'Create device table was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_create_device_table
      @create_device_table = CreateDeviceTable.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def create_device_table_params
      params.require(:create_device_table).permit(:nickname, :street_address, :city, :state, :postal_code, :longitude, :latitude, :api_key)
    end
end

app/helpers/create_device_tables_helper.rb
module CreateDeviceTablesHelper
end

app/views/create_device_tables/_form.html.erb
<%= form_with(model: create_device_table, local: true) do |form| %>
  <% if create_device_table.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(create_device_table.errors.count, "error") %> prohibited this create_device_table from being saved:</h2>

      <ul>
      <% create_device_table.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nickname %>
    <%= form.text_field :nickname %>
  </div>

  <div class="field">
    <%= form.label :street_address %>
    <%= form.text_field :street_address %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state %>
  </div>

  <div class="field">
    <%= form.label :postal_code %>
    <%= form.text_field :postal_code %>
  </div>

  <div class="field">
    <%= form.label :longitude %>
    <%= form.text_field :longitude %>
  </div>

  <div class="field">
    <%= form.label :latitude %>
    <%= form.text_field :latitude %>
  </div>

  <div class="field">
    <%= form.label :api_key %>
    <%= form.text_field :api_key %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/create_device_tables/edit.html.erb
<h1>Editing Create Device Table</h1>

<%= render 'form', create_device_table: @create_device_table %>

<%= link_to 'Show', @create_device_table %> |
<%= link_to 'Back', create_device_tables_path %>

app/views/create_device_tables/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Create Device Tables</h1>

<table>
  <thead>
    <tr>
      <th>Nickname</th>
      <th>Street address</th>
      <th>City</th>
      <th>State</th>
      <th>Postal code</th>
      <th>Longitude</th>
      <th>Latitude</th>
      <th>Api key</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @create_device_tables.each do |create_device_table| %>
      <tr>
        <td><%= create_device_table.nickname %></td>
        <td><%= create_device_table.street_address %></td>
        <td><%= create_device_table.city %></td>
        <td><%= create_device_table.state %></td>
        <td><%= create_device_table.postal_code %></td>
        <td><%= create_device_table.longitude %></td>
        <td><%= create_device_table.latitude %></td>
        <td><%= create_device_table.api_key %></td>
        <td><%= link_to 'Show', create_device_table %></td>
        <td><%= link_to 'Edit', edit_create_device_table_path(create_device_table) %></td>
        <td><%= link_to 'Destroy', create_device_table, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Create Device Table', new_create_device_table_path %>

app/views/create_device_tables/new.html.erb
<h1>New Create Device Table</h1>

<%= render 'form', create_device_table: @create_device_table %>

<%= link_to 'Back', create_device_tables_path %>

app/views/create_device_tables/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nickname:</strong>
  <%= @create_device_table.nickname %>
</p>

<p>
  <strong>Street address:</strong>
  <%= @create_device_table.street_address %>
</p>

<p>
  <strong>City:</strong>
  <%= @create_device_table.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @create_device_table.state %>
</p>

<p>
  <strong>Postal code:</strong>
  <%= @create_device_table.postal_code %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @create_device_table.longitude %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @create_device_table.latitude %>
</p>

<p>
  <strong>Api key:</strong>
  <%= @create_device_table.api_key %>
</p>

<%= link_to 'Edit', edit_create_device_table_path(@create_device_table) %> |
<%= link_to 'Back', create_device_tables_path %>