config/routes.rb
Rails.application.routes.draw do
  resources :ddcs
  resources :attributes
  resources :samples
  resources :create_device_tables

  get 'dashboard', to: 'dashboard#index'

  get 'report', to: 'report#index'

  get 'samples_clear', to: 'samples#clear'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ddc.rb
class Ddc < ApplicationRecord
end

app/controllers/ddcs_controller.rb
class DdcsController < ApplicationController
  before_action :set_ddc, only: [:show, :edit, :update, :destroy]

  # GET /ddcs
  # GET /ddcs.json
  def index
    @ddcs = Ddc.all

    respond_to do |format|
      format.html
      format.json { render json: @ddcs.map { |ddc| ddc.name } }
    end
  end

  # GET /ddcs/1
  # GET /ddcs/1.json
  def show
  end

  # GET /ddcs/new
  def new
    @ddc = Ddc.new
  end

  # GET /ddcs/1/edit
  def edit
  end

  # POST /ddcs
  # POST /ddcs.json
  def create
    @ddc = Ddc.new(ddc_params)

    respond_to do |format|
      if @ddc.save
        format.html { redirect_to @ddc, notice: 'Ddc was successfully created.' }
        format.json { render :show, status: :created, location: @ddc }
      else
        format.html { render :new }
        format.json { render json: @ddc.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ddcs/1
  # PATCH/PUT /ddcs/1.json
  def update
    respond_to do |format|
      if @ddc.update(ddc_params)
        format.html { redirect_to @ddc, notice: 'Ddc was successfully updated.' }
        format.json { render :show, status: :ok, location: @ddc }
      else
        format.html { render :edit }
        format.json { render json: @ddc.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ddcs/1
  # DELETE /ddcs/1.json
  def destroy
    @ddc.destroy
    respond_to do |format|
      format.html { redirect_to ddcs_url, notice: 'Ddc was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ddc
      @ddc = Ddc.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ddc_params
      params.require(:ddc).permit(:name)
    end
end

app/helpers/ddcs_helper.rb
module DdcsHelper
end

app/views/ddcs/_form.html.erb
<%= form_with(model: ddc, local: true) do |form| %>
  <% if ddc.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ddc.errors.count, "error") %> prohibited this ddc from being saved:</h2>

      <ul>
      <% ddc.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ddcs/edit.html.erb
<h1>Editing Ddc</h1>

<%= render 'form', ddc: @ddc %>

<%= link_to 'Show', @ddc %> |
<%= link_to 'Back', ddcs_path %>

app/views/ddcs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ddcs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ddcs.each do |ddc| %>
      <tr>
        <td><%= ddc.name %></td>
        <td><%= link_to 'Show', ddc %></td>
        <td><%= link_to 'Edit', edit_ddc_path(ddc) %></td>
        <td><%= link_to 'Destroy', ddc, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ddc', new_ddc_path %>

app/views/ddcs/new.html.erb
<h1>New Ddc</h1>

<%= render 'form', ddc: @ddc %>

<%= link_to 'Back', ddcs_path %>

app/views/ddcs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ddc.name %>
</p>

<%= link_to 'Edit', edit_ddc_path(@ddc) %> |
<%= link_to 'Back', ddcs_path %>